sudo: false
language: node_js
git:
  depth: 3
node_js:
  - "8"
  - "10"
before_install:
  - "export TRAVIS_COMMIT_MSG=\"`git log --format=%B --no-merges -n 1`\""
  - if [[ `npm -v` == 3* ]]; then npm i -g npm; fi
install:
  - npm install
script:
  - npm run eslint
  - npm test
  - commitlint-travis
notifications:
  slack: indec-sistemas:U34T7wkSbzuMWCcXIw9DOY05
