sudo: false
dist: bionic
language: node_js
git:
  depth: 3
node_js:
  - "8"
  - "10"
before_install:
  - "export TRAVIS_COMMIT_MSG=\"`git log --format=%B --no-merges -n 1`\""
script:
  - npm test
  - commitlint-travis
cache:
  directories:
    - node_modules
